# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=20, verbose_name='Имя')),
                ('sorname', models.CharField(default=' sorname', max_length=20, verbose_name='Фамилия')),
                ('number', models.IntegerField(default='+380', max_length=13, verbose_name='Номер телефона')),
                ('birthday', models.DateField(default='00/00/0000', verbose_name='День рождения')),
                ('info', models.TextField(max_length=100, verbose_name='Дополнительно')),
            ],
        ),
    ]
