# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedApp', '0003_auto_20170419_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usluga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='none', max_length=30, verbose_name='Название процедуры')),
            ],
        ),
        migrations.CreateModel(
            name='UslugaDlaClienta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.IntegerField(default=0, verbose_name='Цена')),
                ('foreign_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedApp.Client')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedApp.Usluga')),
            ],
        ),
    ]
