# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 10:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedApp', '0004_usluga_uslugadlaclienta'),
    ]

    operations = [
        migrations.AddField(
            model_name='usluga',
            name='info',
            field=models.TextField(default='none', max_length=100, verbose_name='Дополнительно'),
        ),
        migrations.AddField(
            model_name='uslugadlaclienta',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 4, 19, 12, 43, 27, 78200)),
        ),
        migrations.AlterField(
            model_name='client',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2017, 4, 19, 12, 43, 27, 75200), verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='client',
            name='number',
            field=models.IntegerField(default='380', verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='client',
            name='sorname',
            field=models.CharField(max_length=20, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='usluga',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Название процедуры'),
        ),
    ]
