# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 20:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedApp', '0005_auto_20170419_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='token',
            field=models.CharField(default='admin_url', max_length=32, verbose_name='Токен'),
        ),
        migrations.AlterField(
            model_name='client',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2017, 4, 19, 22, 35, 33, 164700), verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='uslugadlaclienta',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 4, 19, 22, 35, 33, 166700)),
        ),
    ]
