# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 21:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedApp', '0006_auto_20170419_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='uslugadlaclienta',
            name='method_cash',
            field=models.IntegerField(default=0, verbose_name='Цена препарата'),
        ),
        migrations.AlterField(
            model_name='client',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2017, 4, 19, 23, 43, 44, 700800), verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='uslugadlaclienta',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 4, 19, 23, 43, 44, 702800)),
        ),
    ]
