# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 18:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedApp', '0008_auto_20170420_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='usluga',
            name='token',
            field=models.CharField(default='admin_url_service', max_length=32, verbose_name='Токен'),
        ),
        migrations.AlterField(
            model_name='client',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2017, 4, 23, 20, 52, 31, 680400), verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='uslugadlaclienta',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 4, 23, 20, 52, 31, 684400), verbose_name='Дата процедуры'),
        ),
    ]
