# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedApp', '0009_auto_20170423_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='registration_date',
            field=models.DateTimeField(default='2017-04-25', verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='client',
            name='birthday',
            field=models.DateField(default='2017-04-25', verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='uslugadlaclienta',
            name='date',
            field=models.DateField(default='2017-04-25', verbose_name='Дата процедуры'),
        ),
    ]
