# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedApp', '0011_auto_20170425_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-registration_date']},
        ),
        migrations.AlterModelOptions(
            name='usluga',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='uslugadlaclienta',
            name='info',
            field=models.TextField(default='none', max_length=100, verbose_name='Дополнительно'),
        ),
        migrations.AlterField(
            model_name='client',
            name='registration_date',
            field=models.DateTimeField(default='2017-04-25 21:08', verbose_name='Дата регистрации'),
        ),
    ]
