# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedApp', '0013_auto_20170501_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='number',
            field=models.IntegerField(default=None, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='client',
            name='registration_date',
            field=models.DateTimeField(default='2017-05-01 23:38', verbose_name='Дата регистрации'),
        ),
    ]
