# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedApp', '0015_auto_20170505_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='registration_date',
            field=models.DateTimeField(default='2017-05-09 00:07', verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='uslugadlaclienta',
            name='date',
            field=models.DateField(default='2017-05-09', verbose_name='Дата процедуры'),
        ),
        migrations.AlterField(
            model_name='uslugadlaclienta',
            name='info',
            field=models.TextField(default=None, max_length=100, verbose_name='Дополнительно'),
        ),
        migrations.AlterField(
            model_name='uslugadlaclienta',
            name='medicine',
            field=models.CharField(default=None, max_length=30, verbose_name='Название препарата'),
        ),
    ]
