# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-14 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedApp', '0016_auto_20170509_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='uslugadlaclienta',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время процедуры'),
        ),
        migrations.AlterField(
            model_name='client',
            name='registration_date',
            field=models.DateTimeField(default='2017-05-14 22:47', verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='uslugadlaclienta',
            name='date',
            field=models.DateField(default='2017-05-14', verbose_name='Дата процедуры'),
        ),
    ]
