# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedApp', '0017_auto_20170514_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='registration_date',
            field=models.DateTimeField(default='2017-05-15 15:50', verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='uslugadlaclienta',
            name='date',
            field=models.DateField(default='2017-05-15', verbose_name='Дата процедуры'),
        ),
        migrations.AlterField(
            model_name='uslugadlaclienta',
            name='income',
            field=models.IntegerField(verbose_name='Заработок'),
        ),
        migrations.AlterField(
            model_name='uslugadlaclienta',
            name='info',
            field=models.TextField(blank=True, default=None, max_length=100, null=True, verbose_name='Дополнительно'),
        ),
        migrations.AlterField(
            model_name='uslugadlaclienta',
            name='medicine',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Название препарата'),
        ),
    ]
