# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedApp', '0018_auto_20170515_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='uslugadlaclienta',
            name='token',
            field=models.CharField(default='admin_url', max_length=8, verbose_name='Токен'),
        ),
        migrations.AlterField(
            model_name='client',
            name='registration_date',
            field=models.DateTimeField(default='2017-05-15 16:08', verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='usluga',
            name='token',
            field=models.CharField(default='admin_url_service', max_length=8, verbose_name='Токен'),
        ),
    ]
