# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-27 12:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MedApp', '0019_auto_20170515_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uslugadlaclienta',
            old_name='foreign_key',
            new_name='client',
        ),
        migrations.AddField(
            model_name='uslugadlaclienta',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='client',
            name='registration_date',
            field=models.DateTimeField(default='2017-05-27 15:03', verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='uslugadlaclienta',
            name='date',
            field=models.DateField(default='2017-05-27', verbose_name='Дата процедуры'),
        ),
        migrations.AlterField(
            model_name='uslugadlaclienta',
            name='info',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Дополнительно'),
        ),
    ]
