# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-27 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedApp', '0020_auto_20170527_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uslugadlaclienta',
            old_name='client',
            new_name='foreign_key',
        ),
        migrations.AlterField(
            model_name='client',
            name='registration_date',
            field=models.DateTimeField(default='2017-05-27 15:07', verbose_name='Дата регистрации'),
        ),
    ]
