# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-11 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedApp', '0021_auto_20170527_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='info',
            field=models.TextField(blank=True, default=None, max_length=100, null=True, verbose_name='Дополнительно'),
        ),
        migrations.AlterField(
            model_name='client',
            name='number',
            field=models.CharField(max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='client',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='uslugadlaclienta',
            name='cash',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='uslugadlaclienta',
            name='date',
            field=models.DateField(default='2017-06-11', verbose_name='Дата процедуры'),
        ),
        migrations.AlterField(
            model_name='uslugadlaclienta',
            name='income',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Заработок'),
        ),
        migrations.AlterField(
            model_name='uslugadlaclienta',
            name='info',
            field=models.TextField(blank=True, default=None, max_length=100, null=True, verbose_name='Дополнительно'),
        ),
        migrations.AlterField(
            model_name='uslugadlaclienta',
            name='medicine',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Название препарата'),
        ),
    ]
