# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-18 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedApp', '0022_auto_20170611_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Статус клиента'),
        ),
        migrations.AlterField(
            model_name='uslugadlaclienta',
            name='date',
            field=models.DateField(default='2017-06-18', verbose_name='Дата процедуры'),
        ),
    ]
