# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 20:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MedApp', '0023_auto_20170618_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_name', models.CharField(blank=True, default='User', max_length=30, null=True, verbose_name='Permission')),
                ('add_content', models.BooleanField(default=0, verbose_name='Add content')),
                ('change_content', models.BooleanField(default=0, verbose_name='Change content')),
                ('delete_content', models.BooleanField(default=0, verbose_name='Delete content')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='uslugadlaclienta',
            name='date',
            field=models.DateField(default='2017-10-14', verbose_name='Дата процедуры'),
        ),
    ]
